feat(#6231): Added lsp for `pug`
mason-org/mason-registry pull request #6232
Opened 2024-06-24 07:08 UTC by opa-oz

## Describe your changes

Added LSP for [Pug.js](https://pugjs.org/api/getting-started.html)

LSP: https://github.com/opa-oz/pug-lsp
LspConfig: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/pug.lua

## Issue ticket number and link
#6231 

## Checklist before requesting a review

- [x] I have successfully tested installation of the package.
- [x] I have successfully tested the package after installation.
      

## Screenshots

![Screenshot 2024-06-24 at 16 06 50](https://github.com/mason-org/mason-registry/assets/34550675/efd3026a-b7e5-4fe0-b863-80d5efebab09)
Local registry on the left side - working completion on the right side

`:LspInfo`
![Screenshot 2024-06-24 at 16 07 55](https://github.com/mason-org/mason-registry/assets/34550675/b312e39a-5b89-41a1-80cb-16ecf85d1fa3)

2025-03-25 13:19 UTC, mehalter requested changes
The name of the package should be `pug-lsp`. The `name` field and package folder name should be updated

2025-03-25 13:19 UTC, mehalter commented on packages/pug/package.yaml
> +name: pug
```suggestion
name: pug-lsp
```

2025-03-25 14:55 UTC, Conarius commented on packages/pug/package.yaml
> +name: pug
Changed the name and the title of the pr. Though I wouldn't merge it yet because it does only have 6 stars.

2025-08-01 22:35 UTC, chrisgrieser approved these changes

2025-08-01 22:37 UTC, chrisgrieser commented
@mehalter the changes were made, could you change your review to "approved"? Otherwise merging is blocked.

@opa-oz the tests seems stuck, could you push an empty commit? That should retrigger the tests.

2025-08-01 22:38 UTC, mehalter approved these changes
LGTM!

2025-08-02 00:33 UTC, merged