feat: add vsg formatter
mason-org/mason-registry pull request #8155
Opened 2024-12-07 19:59 UTC by Conarius

## Describe your changes
Add vsg formatter for VHDL files

## Issue ticket number and link

## Checklist before requesting a review

- [x] I have successfully tested installation of the package.
- [x] I have successfully tested the package after installation.
      

## Screenshots

2025-03-25 15:08 UTC, mehalter requested changes
Package name needs to be updated as well as the package folder name

2025-03-25 15:08 UTC, mehalter commented on packages/vsg/package.yaml
> +name: vsg
```suggestion
name: vhdl-style-guide
```

The package name should match the project name first if it's unique rather than the binary name

2025-03-25 20:44 UTC, Conarius commented
> Package name needs to be updated as well as the package folder name

Done

2025-03-28 19:53 UTC, mehalter approved these changes
This looks great and the repo has plenty of stars to be included!

2025-03-28 21:33 UTC, merged

2025-08-11 13:01 UTC, fredrikfoss commented
Hi, this package was already added in #6110. It's a duplicate of the already existing vsg package. Perhaps change the name of the original package to vhdl-style-guide, and have vsg be an alias?