feat(linter): api-linter
mason-org/mason-registry pull request #8277
Opened 2024-12-19 14:39 UTC by fredrikaverpil

## Describe your changes

This PR adds the api-linter binary: https://github.com/googleapis/api-linter

## Issue ticket number and link

## Checklist before requesting a review

- [ ] I have successfully tested installation of the package.
- [ ] I have successfully tested the package after installation.
      

## Screenshots

2025-02-19 06:59 UTC, fredrikaverpil commented
Would it be possible to get this merged in?

2025-03-25 15:28 UTC, mehalter requested changes

2025-03-25 17:18 UTC, fredrikaverpil commented on packages/api-linter/package.yaml
> +  impl: golang:api-linter
Ah, thanks - yes that is correct. Fixed!

2025-03-25 18:14 UTC, mehalter approved these changes
This looks good to me! Once we get a second approval this is good to go

2025-03-29 00:41 UTC, Conarius approved these changes
LGTM

2025-03-29 13:56 UTC, merged